# Generated by Django 4.1.5 on 2023-03-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.CharField(max_length=30)),
                (
                    "principal_debt",
                    models.DecimalField(decimal_places=4, max_digits=23),
                ),
                ("interest_debt", models.DecimalField(decimal_places=4, max_digits=23)),
                ("is_active", models.BooleanField(default=False)),
                ("opening_date", models.DateField(auto_now_add=True)),
                ("closing_date", models.DateField()),
                (
                    "currency_code",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "outstanding_principal",
                    models.DecimalField(decimal_places=4, max_digits=23),
                ),
                (
                    "outstanding_interest_debt",
                    models.DecimalField(decimal_places=4, max_digits=23),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation_type", models.CharField(max_length=30)),
                ("is_debit", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("min_sum", models.DecimalField(decimal_places=4, max_digits=23)),
                ("max_sum", models.DecimalField(decimal_places=4, max_digits=23)),
                (
                    "currency_code",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "min_interest_rate",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "max_interest_rate",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                ("need_guarantees", models.BooleanField(default=False)),
                ("delivery_in_cash", models.BooleanField(default=False)),
                ("early_repayment", models.BooleanField(default=False)),
                ("need_income_details", models.BooleanField(default=False)),
                ("min_period_months", models.IntegerField()),
                ("max_period_months", models.IntegerField()),
                ("is_active", models.BooleanField(default=False)),
                ("details", models.CharField(max_length=255)),
                (
                    "calculation_mode",
                    models.CharField(
                        choices=[
                            ("DIFFERENTIATED", "DIFFERENTIATED"),
                            ("ANNUITY", "ANNUITY"),
                        ],
                        default="DIFFERENTIATED",
                        max_length=30,
                    ),
                ),
                ("grace_period_months", models.IntegerField()),
                ("rate_is_adjustable", models.BooleanField(default=False)),
                ("rate_base", models.CharField(max_length=20)),
                ("rate_fix_part", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "increased_rate",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                ("principal", models.DecimalField(decimal_places=4, max_digits=23)),
                ("interest", models.DecimalField(decimal_places=4, max_digits=23)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_account",
                        to="credit.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sum", models.DecimalField(decimal_places=4, max_digits=23)),
                ("completed_at", models.DateTimeField()),
                ("details", models.CharField(max_length=255)),
                (
                    "currency_code",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_account",
                        to="credit.account",
                    ),
                ),
                (
                    "operation_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_type_related",
                        to="credit.operationtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("REJECT", "REJECT"),
                            ("APPROVED", "APPROVED"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=23)),
                ("period_months", models.IntegerField()),
                ("creation_date", models.DateField(auto_now_add=True)),
                (
                    "monthly_income",
                    models.DecimalField(decimal_places=4, max_digits=23),
                ),
                (
                    "monthly_expenditure",
                    models.DecimalField(decimal_places=4, max_digits=23),
                ),
                ("employer_identification_number", models.CharField(max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oder_product",
                        to="credit.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "credit_type",
                    models.CharField(
                        choices=[
                            ("OVERDRAFT", "OVERDRAFT"),
                            ("REAL_ESTATE", "REAL_ESTATE"),
                            ("INSTALLMENT", "INSTALLMENT"),
                            ("CONSUMER", "CONSUMER"),
                        ],
                        default="CONSUMER",
                        max_length=11,
                    ),
                ),
                ("credit_limit", models.DecimalField(decimal_places=4, max_digits=23)),
                (
                    "currency_code",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("interest_rate", models.DecimalField(decimal_places=4, max_digits=23)),
                ("personal_guarantees", models.BooleanField(default=True)),
                ("grace_period_months", models.IntegerField()),
                ("status", models.CharField(max_length=30)),
                (
                    "late_payment_rate",
                    models.DecimalField(decimal_places=4, max_digits=10),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_order",
                        to="credit.creditorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=16)),
                ("holder_name", models.CharField(max_length=50)),
                ("expiration_date", models.DateField()),
                (
                    "payment_system",
                    models.CharField(
                        choices=[
                            ("VISA", "VISA"),
                            ("MASTERCARD", "MASTERCARD"),
                            ("MIR", "MIR"),
                        ],
                        default="VISA",
                        max_length=30,
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=4, max_digits=23)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BLOCKED", "BLOCKED"),
                            ("ACTIVE", "ACTIVE"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="BLOCKED",
                        max_length=30,
                    ),
                ),
                (
                    "transaction_limit",
                    models.DecimalField(decimal_places=4, max_digits=23),
                ),
                ("delivery_point", models.CharField(max_length=30)),
                ("is_digital_wallet", models.BooleanField(default=False)),
                ("is_virtual", models.BooleanField(default=False)),
                ("co_brand", models.CharField(max_length=30)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_account",
                        to="credit.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                ("agreement_date", models.DateField()),
                ("termination_date", models.DateField()),
                ("responsible_specialist_id", models.CharField(max_length=20)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_credit",
                        to="credit.credit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="credit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_credit",
                to="credit.credit",
            ),
        ),
    ]
