# Generated by Django 4.1.7 on 2023-03-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("credit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="pin",
            field=models.CharField(default=0, max_length=4),
        ),
    ]
