# Generated by Django 4.1.7 on 2023-03-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("credit", "0002_card_pin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentschedule",
            name="account",
        ),
        migrations.AddField(
            model_name="paymentschedule",
            name="credit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_credit",
                to="credit.credit",
            ),
            preserve_default=False,
        ),
    ]
